baseURL: https://humberto.io/
DefaultContentLanguage: en
title: Humberto Rocha
theme: colordrop
enableRobotsTXT: true
disqusShortname: humrochagf
googleAnalytics: UA-62093919-2

markup:
  goldmark:
    renderer:
      unsafe: true

author:
  name: Humberto Rocha
  job: Developer
  gender: male
  image: img/me.jpg
  github: humrochagf
  twitter: humrochagf
  linkedin: humrochagf

taxonomies:
  tag: tags

menu:
  main:
    - identifier: blog
      name: Blog
      url: blog/
      weight: 2
    - identifier: tags
      name: Tags
      url: tags/
      weight: 3
  footer:
    - identifier: github
      name: github
      url: https://github.com/humrochagf/
      weight: 1
    - identifier: twitter
      name: twitter
      url: https://twitter.com/humrochagf/
      weight: 2
    - identifier: linkedin
      name: linkedin
      url: https://linkedin.com/in/humrochagf/
      weight: 3
    - identifier: keybase
      name: keybase
      url: https://keybase.io/humrochagf/
      weight: 4
    - identifier: rss
      name: rss
      weight: 5
    - identifier: curriculum
      name: curriculum
      url: curriculum/
      weight: 6
    - identifier: email
      name: email
      url: mailto:humrochagf@gmail.com
      weight: 7

params:
  title: Humberto Rocha
  description: A blog to put into words a portion of my knowledge about coding, technology, and much more. I hope you find here something that can help you as it helped me before ðŸ˜Š
  images:
    - img/me.jpg
  themeColor: "#000000"
  themeInverseColor: "#ffffff"
  siteLogo: img/me-100x100.jpg

  license:
    name: Attribuition-ShareAlike
    type: by-sa
    version: "4.0"
    locale: en
    size: 88x31

languages:
  en:
    languageName: English
    weight: 1
  pt-br:
    languageName: PortuguÃªs Brasileiro
    weight: 2
    params:
      description: Um blog onde eu coloco em palavras um pouco do meu conhecimento sobre programaÃ§Ã£o, tecnologia e muito mais. Espero que vocÃª encontre aqui algo que possa lhe ajudar, assim como esse conhecimento jÃ¡ me ajudou um dia ðŸ˜Š
      license:
        name: AtribuiÃ§Ã£o-CompartilhaIgual
        type: by-sa
        version: "4.0"
        locale: pt_BR
        size: 88x31
  fr:
    languageName: FranÃ§ais
    weight: 3
    params:
      description: Un blog ou je met en mot une partie de mon savoir a propos de la programmation, de la technologie et plus. J'espÃ¨re que vous trouvez des choses qui puisse vous aider comme Ã§a m'a dÃ©jÃ  aidÃ© ðŸ˜Š
      license:
        name: Attribution - Partage dans les MÃªmes Conditions
        type: by-sa
        version: "4.0"
        locale: fr
        size: 88x31
