---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Posts - English
  create: all
  match: "*.en.md"
  new_doc_ext: en.md
  templates:
  - blog-post-english
- type: directory
  path: content/blog
  label: Posts - Português
  create: all
  match: "*.pt-br.md"
  new_doc_ext: pt-br.md
  templates:
  - blog-post-portugues
- type: directory
  path: content/blog
  label: Posts - Français
  create: all
  match: "*.fr.md"
  new_doc_ext: fr.md
  templates:
  - blog-post-portugues
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
version: 0.55.6
